version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: orcaai-postgres
    environment:
      POSTGRES_DB: orcaai
      POSTGRES_USER: orcaai_user
      POSTGRES_PASSWORD: orcaai_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - orcaai-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: orcaai-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - orcaai-network

  # Backend API Service
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: orcaai-backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=orcaai
      - DB_USER=orcaai_user
      - DB_PASSWORD=orcaai_password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
    networks:
      - orcaai-network

  # Python AI Worker
  ai-worker:
    build:
      context: ../python-ai-worker
      dockerfile: Dockerfile
    container_name: orcaai-ai-worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - orcaai-network

  # Frontend Dashboard
  dashboard:
    build:
      context: ../dashboard
      dockerfile: Dockerfile
    container_name: orcaai-dashboard
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080
    depends_on:
      - backend
    networks:
      - orcaai-network

  # Prometheus for monitoring
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: orcaai-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - orcaai-network

  # Grafana for visualization
  grafana:
    image: grafana/grafana-enterprise
    container_name: orcaai-grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - orcaai-network

volumes:
  postgres_data:
  redis_data:
  grafana_data:

networks:
  orcaai-network:
    driver: bridge