apiVersion: apps/v1
kind: Deployment
metadata:
  name: orcaai-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orcaai-postgres
  template:
    metadata:
      labels:
        app: orcaai-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "orcaai"
        - name: POSTGRES_USER
          value: "orcaai_user"
        - name: POSTGRES_PASSWORD
          value: "orcaai_password"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: orcaai-postgres-service
spec:
  selector:
    app: orcaai-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi